package uk.gov.moj.cpp.sjp.query.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.subscriptions.query.api.accesscontrol.PermissionConstants;


global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;


rule "Query - API - Action -  subscriptions.query.subscriptions"
  when
    $outcome: Outcome();
    $action: Action(name == "subscriptions.query.subscriptions");
    eval(userAndGroupProvider.hasPermission($action, PermissionConstants.getSubscriptionsPermission()));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - Action -  subscriptions.query.subscriptions.by-court-id"
  when
    $outcome: Outcome();
    $action: Action(name == "subscriptions.query.subscriptions.by-court-id");
  then
    $outcome.setSuccess(true);
end

rule "Query - API - Action -  subscriptions.query.subscriptions-by-user"
  when
    $outcome: Outcome();
    $action: Action(name == "subscriptions.query.subscriptions-by-user");
    eval(userAndGroupProvider.hasPermission($action, PermissionConstants.getSubscriberPermission()));
  then
    $outcome.setSuccess(true);
end
